# Generated by Django 5.1.1 on 2025-02-27 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='neo4jserver',
            name='server_password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='neo4jserver',
            name='server_username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='neo4jserver',
            name='url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='neo4jserver',
            unique_together={('user', 'url', 'server_username', 'server_password')},
        ),
    ]
