# Generated by Django 5.1.1 on 2024-10-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neo4jserver',
            name='server_username',
            field=models.CharField(default='default_username', max_length=255),
            preserve_default=False,
        ),
    ]
